### ISSUE TITLE
[Compose] Migrate to the new permission request logic

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-templates#370]
## Why

According to the [Setup the nav graph and navigation logic](https://github.com/nimblehq/android-templates/issues/352) task, we need to migrate all deprecated Fragments into Composables. Hence, migrating legacy permission requests on Fragment to the new approach in Jetpack Compose is needed.

In the end, we will stop using Peko in Compose Template and switch to using https://google.github.io/accompanist/permissions/.

## Who Benefits?

Developers

**Comment by Tuubz** [comment]
@luongvo We broke the rules of our wiki for this issue:

- Every issue needs to go through a voting process first (unless I missed a discussion/RFC somewhere?)
- Always inform the repository maintainer before adding any issue to the sprint, otherwise we risk overestimating

Since you already created a PR for this, let's keep it, but please keep it in mind for next time 🙏

**Comment by Tuubz** [comment]
@luongvo We broke the rules of our wiki for this issue:

- Every issue needs to go through a voting process first (unless I missed a discussion/RFC somewhere?)
- Always inform the repository maintainer before adding any issue to the sprint, otherwise, we risk overestimating

Since you already created a PR for this, let's keep it, but please keep it in mind for next time 🙏

**Comment by luongvo** [comment]
@Tuubz Ah yes, sorry for the issue 🙏 

Actually, I intended to do it in the same PR of https://github.com/nimblehq/android-templates/issues/352 when removing the deprecated stuff of the XML method. Then I thought, a separate PR and a separate ticket would be better for it.
