### ISSUE TITLE
[Compose] Add a sample to navigate to the ThirdScreen with a custom parcelable data

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-templates#377]
## Why

Coming through [this discussion](https://github.com/nimblehq/android-templates/pull/372#discussion_r1058045844), we need to have a sample implementation to demonstrate how can we pass a parcelable data between destinations. Unfortunately, it's not that easy:
- https://betterprogramming.pub/realize-jetpack-compose-navigation-2889401f52b
- https://stackoverflow.com/questions/65610003/pass-parcelable-argument-with-compose-navigation
- https://stackoverflow.com/questions/67553012/passing-model-between-destinations/67553630#67553630
- https://gist.github.com/Aidanvii7/46f9f014ba4dc58a2ac10625b198769d

We should find an optimized way to apply it to the template.

## Who Benefits?

Developers

**Comment by Tuubz** [comment]
@luongvo Should we instead of creating another third screen, re-use the second screen?

Then we can replace "passing a string" with "passing an object" 💭

**Comment by luongvo** [comment]
@Tuubz I think we're having the same issue with https://github.com/nimblehq/android-templates/pull/375#discussion_r1058239429. Do you want to have 2 samples (passing with primitive data type & parcelable) or only passing parcelable? IMO, both of them require complex implementation so I recommend to have a separation.

**Comment by Tuubz** [comment]
@luongvo Hmmm, I see 👍 

How would you design the third screen? A new button on the home screen or the second screen? 💭

**Comment by luongvo** [comment]
> @luongvo Hmmm, I see 👍
> 
> How would you design the third screen? A new button on the home screen or the second screen? 💭

@Tuubz Nice question. I initiated it by randomly navigating to the Second or the Third screen from the Home's list item. 🤔 
We can navigate to the Second screen by `uiModel.id` or the Third screen by `uiModel`.

**Comment by luongvo** [comment]
The UI should be the same together, one displays the id in the middle, one shows the whole parcelable model as string.

**Comment by Tuubz** [comment]
Alright, let's do it that way 🚀

**Comment by Tuubz** [comment]
@luongvo Can I assign this issue to someone else? You already have 2 issues for this sprint 🙏

**Comment by luongvo** [comment]
Yes please 👍 I think those 3 articles are enough to go.

**Comment by kaungkhantsoe** [comment]
I have tried out the ways from the links and nothing works for me. We are currently using compose navigation version `2.5.1` and I think most of the workaround described in the links have been outdated since `2.4.0-alpha`. For example, `navController.currentBackStackEntry?.arguments` used to be `var` and it is used to pass the object. With the current version, `arguments` becomes `val` and cannot use it anymore. I found [this workaround](https://stackoverflow.com/a/67133534) and it works. We will be just converting the whole object to `Json` before passing the object. There is a catch. Since we are converting the object, it could block the thread if the object is too big. What do you guys think about it? @luongvo @Tuubz

**Comment by Tuubz** [comment]
Damn, bad luck 😨 cc @hoangnguyen92dn

**Comment by hoangnguyen92dn** [comment]
@kaungkhantsoe Just want to make sure, did you try with the latest stable version (`2.5.3`) of [compose-navigation](https://developer.android.com/jetpack/androidx/releases/navigation) yet? 😄 It still contains the [NavType](https://developer.android.com/reference/kotlin/androidx/navigation/NavType) class that supports `Parcelable` and `Serializable` for argument type, which means that we can define the object/model as the argument on navigation graph. 

Regarding the `navController.currentBackStackEntry?.arguments`, the new approach should use the `savedStateHandle` rather than the `arguments`.

As you mentioned about the advise to not passing complex data, I guess you are referencing [this](https://developer.android.com/jetpack/compose/navigation#retrieving-complex-data) 

> It is strongly advised not to pass around complex data objects when navigating, but instead pass the minimum necessary information, such as a unique identifier or other form of ID, as arguments when performing navigation actions:

But they also mentioned about storing the data on `savedStateHandle`:

> Complex objects should be stored as data in a single source of truth, such as the data layer

How do you think about this approach? cc @Tuubz @luongvo

**Comment by kaungkhantsoe** [comment]
@hoangnguyen92dn Please correct me if I am wrong. 🙏  I tried something like this

```
  object Third: AppDestination("third/{$ModelKey}") {
        override val arguments = listOf(
            navArgument(ModelKey) { type = NavType.ParcelableType(ModelKey::class.java)}
        )
        fun createRoute(model: UiModel) = apply {
            destination = "third/$model"
        }
    }
```
And I got `java.lang.UnsupportedOperationException: Parcelables don't support default values.` error. I also found [this](https://stackoverflow.com/a/68008954) workaround but it is apparently the same as my previous solution. I also read about the `savedStateHandle`. Isn't it [to handle system-initiated process death](https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-savedstate#setup)? 💭

**Comment by hoangnguyen92dn** [comment]
@kaungkhantsoe Regarding the `savedStateHandle`, there is `savedStateHandle` instance in the `backStackEntry` (include: `previousBackStackEntry` and `currentBackStackEntry`) beside the arguments.

![image](https://user-images.githubusercontent.com/6950766/212260726-f9be8dae-497a-4ff4-8915-dba982bdbfdc.png)

Let's clarify the idea with an example; there are two screens: Home > Detail, we need to pass `UiModel` from Home to Detail screen.

In the Home screen, we could store the data in `savedStateHandle` by:

```
navController.currentBackStackEntry?.savedStateHandle?.set(
                "key",
                uiModel
            )
``` 

On the Detail screen, we could get the `uiModel` via `savedStateHandle`:

```
navController.previousBackStackEntry?.savedStateHandle?.get<UiModel>(
                    "key"
                )
```

How do you think about this approach? @kaungkhantsoe

**Comment by luongvo** [comment]
@hoangnguyen92dn @Tuubz @kaungkhantsoe This issue should be moved to Slack discussion to speed up the conversation guys 👋

**Comment by hoangnguyen92dn** [comment]
@luongvo I think better to use Github discussion instead 😄
