### ISSUE TITLE
Apply ViewBinding

### ISSUE THREAD

**Issue by hoangnguyen92dn** [nimblehq/android-templates#83]
## Why

**Descriptions**
ViewBinding is a part of Android Jetpack with replaced findViewById and kotlin synthetic extension
> View binding is a feature that allows you to more easily write code that interacts with views. Once view binding is enabled in a module, it generates a binding class for each XML layout file present in that module. An instance of a binding class contains direct references to all views that have an ID in the corresponding layout.

:white_check_mark: **Acceptance Criteria**
- [x] Apply ViewBinding to UI on the RxJava template
- [x] Apply ViewBinding to UI on the Coroutine template
- [x] Adding UnitTest with ViewBinding

## Who Benefits?

Android chapter

**Comment by sleepylee** [comment]
@manh-t kindly update the status on this so the others can follow up 🙇

**Comment by manh-t** [comment]
Sorry for the late on this issue. 🙇 Last time I tried, I was stuck with an issue that couldn't find a generated View class from ViewBinding, so I was unable to write the Fragment/ Activity test. Maybe it is because of missing dependencies or something related.
Currently, I'm re-visiting the ViewBinding implementation and trying to add the unit test.
Will update the result asap. 🙏

**Comment by manh-t** [comment]
@hoangnguyen92dn @lydiasama this issue is resolved. 🙏

**Comment by luongvo** [comment]
@manh-t you can close it, attach the issue to the PR then merging the PR will close the issue automatically on the board 🤔

**Comment by manh-t** [comment]
@luongvo in case we have multiple tasks to do in an issue, it's better to close the issue manually 🤪  
Okay, I'll close this issue 🙏

**Comment by luongvo** [comment]
@manh-t yes, but you knew your last PR is the last part of this ticket 🤓
